/**
 * Build sat/ (Rust, batsat) to wasm32 and inline it into a TS module as base64.
 *
 * The wasm is committed to the repo *as a source file*, so `npm run build` needs
 * no Rust toolchain — only regenerating it does.  Base64 rather than a .wasm
 * asset because the single-file HTML build has to work from a `file://` page,
 * where fetching a sibling asset is impossible; a string inside the bundle needs
 * no fetch at all.
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const crate = path.join(root, "sat");
const out = path.join(root, "src", "sat.wasm.ts");
const target = "wasm32-unknown-unknown";
const wasm = path.join(crate, "target", target, "release", "linkr_sat.wasm");

console.log(`building sat/ for ${target}…`);
execFileSync(
  "cargo",
  ["build", "--release", "--target", target],
  { cwd: crate, stdio: "inherit" },
);

const bytes = readFileSync(wasm);
const b64 = bytes.toString("base64");
// Split so the generated file has readable lines instead of one 80 kB monster.
const lines = b64.match(/.{1,120}/g) ?? [];

mkdirSync(path.dirname(out), { recursive: true });
writeFileSync(
  out,
  `// GENERATED by scripts/build-sat.mjs — do not edit.
// Source: sat/src/lib.rs (batsat ${JSON.stringify("0.6")}), target ${target}.
// ${bytes.length} bytes of wasm, base64 so it can be inlined into the
// single-file HTML build.
export const SAT_WASM_BASE64 =
${lines.map((l) => `  ${JSON.stringify(l)}`).join(" +\n")};
`,
);

console.log(
  `wrote ${path.relative(root, out)} (${bytes.length} B wasm -> ` +
    `${(b64.length / 1024).toFixed(1)} kB base64)`,
);
